import type { MasterProfile, JobAnalysis, ResumeContent } from './types';

export const MOCK_MASTER_PROFILE: MasterProfile = {
  profile: {
    id: 'mock-profile-1',
    user_id: 'mock-user-1',
    full_name: 'Alex Chen',
    professional_title: 'Senior Full Stack Engineer',
    email: 'alex.chen@email.com',
    phone: '+1 (555) 123-4567',
    location: 'San Francisco, CA',
    website: 'https://alexchen.dev',
    linkedin: 'linkedin.com/in/alexchen',
    github: 'github.com/alexchen',
    avatar_url: '',
    summary:
      'Experienced full-stack engineer with 6+ years building scalable web applications. Passionate about clean architecture, developer experience, and shipping high-impact products that users love.',
    profile_completion: 85,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  education: [
    {
      id: 'edu-1',
      user_id: 'mock-user-1',
      institution: 'University of California, Berkeley',
      degree: 'Bachelor of Science',
      field_of_study: 'Computer Science',
      start_date: '2014-09',
      end_date: '2018-05',
      gpa: '3.8',
      activities: 'ACM, Hackathon Club',
      description: '',
      sort_order: 0,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  workExperience: [
    {
      id: 'exp-1',
      user_id: 'mock-user-1',
      company: 'Stripe',
      role: 'Senior Software Engineer',
      location: 'San Francisco, CA',
      start_date: '2021-03',
      end_date: '',
      is_current: true,
      bullets: [
        'Led migration of payment processing service to microservices architecture, reducing latency by 40%',
        'Built internal developer tooling used by 200+ engineers, improving deploy velocity by 3x',
        'Mentored 4 junior engineers and led bi-weekly technical talks on system design',
        'Designed and shipped the new Stripe Dashboard analytics module serving 500K+ merchants',
      ],
      description: '',
      sort_order: 0,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'exp-2',
      user_id: 'mock-user-1',
      company: 'Airbnb',
      role: 'Software Engineer',
      location: 'San Francisco, CA',
      start_date: '2018-07',
      end_date: '2021-02',
      is_current: false,
      bullets: [
        'Developed guest checkout flow improvements that increased conversion rate by 12%',
        'Built real-time search infrastructure handling 10M+ queries/day using Elasticsearch',
        'Contributed to open-source React component library with 8K+ GitHub stars',
        'Collaborated with design team to implement new host onboarding experience',
      ],
      description: '',
      sort_order: 1,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      user_id: 'mock-user-1',
      name: 'OpenDash',
      description: 'Open-source analytics dashboard framework with real-time data streaming',
      tech_stack: ['React', 'TypeScript', 'WebSockets', 'PostgreSQL', 'Docker'],
      live_url: 'https://opendash.dev',
      repo_url: 'https://github.com/alexchen/opendash',
      start_date: '2022-01',
      end_date: '2023-06',
      highlights: [
        '2,400+ GitHub stars',
        'Used by 50+ companies in production',
        'Featured in React Weekly newsletter',
      ],
      sort_order: 0,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  skills: [
    { id: 's1', user_id: 'mock-user-1', name: 'TypeScript', category: 'Languages', proficiency: 'Expert', sort_order: 0, created_at: '2024-01-01T00:00:00Z' },
    { id: 's2', user_id: 'mock-user-1', name: 'React', category: 'Frontend', proficiency: 'Expert', sort_order: 1, created_at: '2024-01-01T00:00:00Z' },
    { id: 's3', user_id: 'mock-user-1', name: 'Node.js', category: 'Backend', proficiency: 'Expert', sort_order: 2, created_at: '2024-01-01T00:00:00Z' },
    { id: 's4', user_id: 'mock-user-1', name: 'PostgreSQL', category: 'Databases', proficiency: 'Advanced', sort_order: 3, created_at: '2024-01-01T00:00:00Z' },
    { id: 's5', user_id: 'mock-user-1', name: 'AWS', category: 'Cloud', proficiency: 'Advanced', sort_order: 4, created_at: '2024-01-01T00:00:00Z' },
    { id: 's6', user_id: 'mock-user-1', name: 'Go', category: 'Languages', proficiency: 'Intermediate', sort_order: 5, created_at: '2024-01-01T00:00:00Z' },
    { id: 's7', user_id: 'mock-user-1', name: 'Docker', category: 'DevOps', proficiency: 'Advanced', sort_order: 6, created_at: '2024-01-01T00:00:00Z' },
    { id: 's8', user_id: 'mock-user-1', name: 'Kubernetes', category: 'DevOps', proficiency: 'Intermediate', sort_order: 7, created_at: '2024-01-01T00:00:00Z' },
    { id: 's9', user_id: 'mock-user-1', name: 'GraphQL', category: 'Backend', proficiency: 'Advanced', sort_order: 8, created_at: '2024-01-01T00:00:00Z' },
    { id: 's10', user_id: 'mock-user-1', name: 'Redis', category: 'Databases', proficiency: 'Advanced', sort_order: 9, created_at: '2024-01-01T00:00:00Z' },
  ],
  certifications: [
    {
      id: 'cert-1',
      user_id: 'mock-user-1',
      name: 'AWS Certified Solutions Architect',
      issuer: 'Amazon Web Services',
      issue_date: '2022-08',
      expiry_date: '2025-08',
      credential_id: 'AWS-SAA-12345',
      credential_url: 'https://aws.amazon.com/certification',
      sort_order: 0,
      created_at: '2024-01-01T00:00:00Z',
    },
  ],
  links: [
    { id: 'link-1', user_id: 'mock-user-1', label: 'Portfolio', url: 'https://alexchen.dev', sort_order: 0, created_at: '2024-01-01T00:00:00Z' },
    { id: 'link-2', user_id: 'mock-user-1', label: 'Tech Blog', url: 'https://blog.alexchen.dev', sort_order: 1, created_at: '2024-01-01T00:00:00Z' },
  ],
  campusActivities: [],
};

export const MOCK_JOB_ANALYSIS: JobAnalysis = {
  keywords: ['TypeScript', 'React', 'Node.js', 'microservices', 'REST API', 'CI/CD', 'Agile', 'system design'],
  requirements: [
    '5+ years of full-stack development experience',
    'Strong proficiency in TypeScript and React',
    'Experience with cloud infrastructure (AWS/GCP)',
    'Familiarity with microservices architecture',
    'Strong communication and collaboration skills',
  ],
  responsibilities: [
    'Design and build scalable backend services',
    'Collaborate with product and design teams',
    'Lead technical discussions and code reviews',
    'Mentor junior engineers',
    'Drive best practices for software quality',
  ],
  ats_terms: ['full-stack', 'scalable', 'microservices', 'agile', 'CI/CD', 'cloud-native', 'REST API'],
  match_score: 87,
  gaps: ['Python experience preferred', 'ML/AI background a plus', 'GraphQL Federation not mentioned'],
  matched_skills: ['TypeScript', 'React', 'Node.js', 'AWS', 'PostgreSQL', 'Docker'],
  seniority_level: 'Senior',
  industry: 'FinTech / SaaS',
};

export const MOCK_RESUME_CONTENT: ResumeContent = {
  header: {
    name: 'Alex Chen',
    title: 'Senior Full Stack Engineer',
    email: 'alex.chen@email.com',
    phone: '+1 (555) 123-4567',
    location: 'San Francisco, CA',
    linkedin: 'linkedin.com/in/alexchen',
    github: 'github.com/alexchen',
    website: 'alexchen.dev',
  },
  summary:
    'Senior Full Stack Engineer with 6+ years building scalable TypeScript and React applications. Proven track record delivering microservices architecture, CI/CD pipelines, and mentoring high-performing engineering teams in fast-paced FinTech environments.',
  experience: [
    {
      id: 'exp-1',
      company: 'Stripe',
      role: 'Senior Software Engineer',
      location: 'San Francisco, CA',
      start_date: '2021-03',
      end_date: '',
      is_current: true,
      bullets: [
        'Led migration of payment processing service to microservices architecture, reducing latency by 40%',
        'Built internal developer tooling and CI/CD pipelines used by 200+ engineers, improving deploy velocity by 3x',
        'Mentored 4 junior engineers and led bi-weekly technical talks on system design',
      ],
    },
    {
      id: 'exp-2',
      company: 'Airbnb',
      role: 'Software Engineer',
      location: 'San Francisco, CA',
      start_date: '2018-07',
      end_date: '2021-02',
      is_current: false,
      bullets: [
        'Developed guest checkout flow improvements using React and TypeScript, increasing conversion by 12%',
        'Built REST API and real-time search infrastructure handling 10M+ queries/day',
      ],
    },
  ],
  education: [
    {
      id: 'edu-1',
      institution: 'University of California, Berkeley',
      degree: 'Bachelor of Science',
      field_of_study: 'Computer Science',
      start_date: '2014-09',
      end_date: '2018-05',
      gpa: '3.8',
    },
  ],
  skills: [
    { category: 'Languages', items: ['TypeScript', 'JavaScript', 'Go'] },
    { category: 'Frontend', items: ['React', 'Next.js'] },
    { category: 'Backend', items: ['Node.js', 'REST API', 'GraphQL'] },
    { category: 'Cloud & DevOps', items: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'] },
    { category: 'Databases', items: ['PostgreSQL', 'Redis'] },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'OpenDash',
      description: 'Open-source analytics dashboard framework with real-time data streaming',
      tech_stack: ['React', 'TypeScript', 'WebSockets', 'PostgreSQL'],
      live_url: 'https://opendash.dev',
      repo_url: 'https://github.com/alexchen/opendash',
      highlights: ['2,400+ GitHub stars', 'Used by 50+ companies in production'],
    },
  ],
  campusActivities: [],
  certifications: [
    {
      id: 'cert-1',
      name: 'AWS Certified Solutions Architect',
      issuer: 'Amazon Web Services',
      issue_date: '2022-08',
    },
  ],
};
